# Generated by Django 5.2.5 on 2025-09-11 13:37

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ready_dress', 'Ready Dress'), ('fabric_only', 'Fabric Only')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='fit_feedback',
            field=models.CharField(blank=True, choices=[('tight', 'Tight'), ('a_little_tight', 'A Little Tight'), ('just_right', 'Just Right'), ('a_little_loose', 'A Little Loose'), ('loose', 'Loose')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='length_feedback',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('a_little_short', 'A Little Short'), ('just_right', 'Just Right'), ('a_little_long', 'A Little Long'), ('long', 'Long')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='transparency_feedback',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
