# Generated by Django 5.2.5 on 2025-09-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productrating_options_remove_product_fabric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
