# Generated by Django 5.2.5 on 2025-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_color_remove_orderitem_product_and_more'),
        ('products', '0005_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('poshak', 'Poshak'), ('dupatta', 'Dupatta'), ('suit', 'Suit'), ('odhna', 'Odhna')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('georgette', 'Georgette'), ('velvet', 'Velvet')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', '2XL')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
