# Generated by Django 5.2.5 on 2025-09-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
