# Generated by Django 5.2.5 on 2025-09-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='fit_feedback',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='length_feedback',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='transparency_feedback',
        ),
    ]
