# Generated by Django 5.2.5 on 2025-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productrating_fit_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Poshak', 'Poshak'), ('Dupatta', 'Dupatta'), ('Suit', 'Suit'), ('Odhna', 'Odhna')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Silk', 'Silk'), ('Georgette', 'Georgette'), ('Velvet', 'Velvet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL')], max_length=5, null=True),
        ),
    ]
