# Generated by Django 5.2.5 on 2025-10-28 03:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_product_type_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Poshak', 'Poshak'), ('Dupatta', 'Dupatta'), ('Suit', 'Suit'), ('Odhna', 'Odhna'), ('Lehenga', 'Lehenga')], max_length=50),
        ),
    ]
